### ISSUE TITLE
ModuleNotFoundError: No module named 'pubchempy'

### ISSUE THREAD

**Issue by Ash100** [Chemoinfomatics/pyqsar3#6]
Hello, Thanks for updating the Readme section and bringing the environment file. Despite this, import is failing with the mentioned error in the title. I can confirm that all the mentioned programs were successfully installed from environment.yml and in particular pubchempy-1.0.4 was successfully installed. I going to paste the installation log below;

> Cloning into 'pyqsar3'...
remote: Enumerating objects: 115, done.
remote: Counting objects: 100% (115/115), done.
remote: Compressing objects: 100% (108/108), done.
remote: Total 115 (delta 20), reused 11 (delta 5), pack-reused 0
Receiving objects: 100% (115/115), 33.59 MiB | 14.11 MiB/s, done.
Resolving deltas: 100% (20/20), done.
/content/pyqsar3
Channels:
 - conda-forge
 - salilab
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done
Please update conda by running

    $ conda update -n base -c conda-forge conda

Downloading and Extracting Packages:

Requirement already satisfied: traitlets>=4.3.1 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from ipywidgets==8.0.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 1)) (5.14.1)
Requirement already satisfied: ipython>=6.1.0 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from ipywidgets==8.0.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 1)) (7.31.1)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from ipywidgets==8.0.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 1)) (6.19.2)
Collecting widgetsnbextension~=4.0
  Downloading widgetsnbextension-4.0.10-py3-none-any.whl (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 101.3 MB/s eta 0:00:00
Collecting jupyterlab-widgets~=3.0
  Downloading jupyterlab_widgets-3.0.10-py3-none-any.whl (215 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 215.0/215.0 kB 31.0 MB/s eta 0:00:00
Requirement already satisfied: cycler>=0.10 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from matplotlib==3.7.1->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 2)) (0.12.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from matplotlib==3.7.1->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 2)) (9.3.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from matplotlib==3.7.1->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 2)) (4.33.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from matplotlib==3.7.1->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 2)) (2.9.0)
Collecting contourpy>=1.0.1
  Downloading contourpy-1.2.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (310 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.0/311.0 kB 36.9 MB/s eta 0:00:00
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from matplotlib==3.7.1->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 2)) (1.4.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from matplotlib==3.7.1->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 2)) (3.1.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from matplotlib==3.7.1->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 2)) (24.0)
Requirement already satisfied: importlib-resources>=3.2.0 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from matplotlib==3.7.1->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 2)) (6.1.3)
Collecting dash>=2.0.0
  Downloading dash-2.16.1-py3-none-any.whl (10.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 59.8 MB/s eta 0:00:00
Requirement already satisfied: werkzeug>=2.0.0 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from molplotly==1.1.7->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 3)) (2.2.2)
Collecting jupyter-dash>=0.4.2
  Downloading jupyter_dash-0.4.2-py3-none-any.whl (23 kB)
Requirement already satisfied: nbformat in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from molplotly==1.1.7->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 3)) (5.9.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from pandas==1.5.3->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 6)) (2024.1)
Requirement already satisfied: panel in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from panel-chemistry==0.2.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 7)) (0.14.3)
Collecting tenacity>=6.2.0
  Downloading tenacity-8.2.3-py3-none-any.whl (24 kB)
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.7/151.7 kB 22.2 MB/s eta 0:00:00
Requirement already satisfied: requests>=2.0.0 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from requests-oauthlib==1.3.1->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 12)) (2.28.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from scikit-learn==1.2.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 13)) (3.3.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from scikit-learn==1.2.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 13)) (1.3.2)
Requirement already satisfied: setuptools in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from dash>=2.0.0->molplotly==1.1.7->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 3)) (69.1.1)
Collecting dash-table==5.0.0
  Downloading dash_table-5.0.0-py3-none-any.whl (3.9 kB)
Requirement already satisfied: importlib-metadata in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from dash>=2.0.0->molplotly==1.1.7->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 3)) (7.0.2)
Collecting retrying
  Downloading retrying-1.3.4-py3-none-any.whl (11 kB)
Collecting dash-core-components==2.0.0
  Downloading dash_core_components-2.0.0-py3-none-any.whl (3.8 kB)
Requirement already satisfied: Flask<3.1,>=1.0.4 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from dash>=2.0.0->molplotly==1.1.7->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 3)) (2.2.2)
Collecting dash-html-components==2.0.0
  Downloading dash_html_components-2.0.0-py3-none-any.whl (4.1 kB)
Requirement already satisfied: nest-asyncio in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from dash>=2.0.0->molplotly==1.1.7->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 3)) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from dash>=2.0.0->molplotly==1.1.7->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 3)) (4.10.0)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib==3.7.1->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 2)) (3.17.0)
Requirement already satisfied: tornado>=6.1 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets==8.0.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 1)) (6.1)
Requirement already satisfied: psutil in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets==8.0.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 1)) (5.9.1)
Requirement already satisfied: debugpy>=1.0 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets==8.0.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 1)) (1.6.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets==8.0.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 1)) (7.3.4)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets==8.0.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 1)) (0.1.6)
Requirement already satisfied: comm>=0.1.1 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets==8.0.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 1)) (0.2.1)
Requirement already satisfied: pyzmq>=17 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets==8.0.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 1)) (23.0.0)
Requirement already satisfied: pygments in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from ipython>=6.1.0->ipywidgets==8.0.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 1)) (2.17.2)
Requirement already satisfied: backcall in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from ipython>=6.1.0->ipywidgets==8.0.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 1)) (0.2.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from ipython>=6.1.0->ipywidgets==8.0.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 1)) (0.18.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from ipython>=6.1.0->ipywidgets==8.0.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 1)) (4.9.0)
Requirement already satisfied: pickleshare in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from ipython>=6.1.0->ipywidgets==8.0.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 1)) (0.7.5)
Requirement already satisfied: decorator in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from ipython>=6.1.0->ipywidgets==8.0.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 1)) (5.1.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from ipython>=6.1.0->ipywidgets==8.0.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 1)) (3.0.42)
Collecting ansi2html
  Downloading ansi2html-1.9.1-py3-none-any.whl (17 kB)
Requirement already satisfied: six>=1.5 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib==3.7.1->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from requests>=2.0.0->requests-oauthlib==1.3.1->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 12)) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from requests>=2.0.0->requests-oauthlib==1.3.1->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 12)) (2024.2.2)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from requests>=2.0.0->requests-oauthlib==1.3.1->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 12)) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from requests>=2.0.0->requests-oauthlib==1.3.1->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 12)) (3.6)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from werkzeug>=2.0.0->molplotly==1.1.7->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 3)) (2.1.1)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from nbformat->molplotly==1.1.7->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 3)) (4.21.1)
Requirement already satisfied: fastjsonschema in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from nbformat->molplotly==1.1.7->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 3)) (2.19.1)
Requirement already satisfied: jupyter-core in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from nbformat->molplotly==1.1.7->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 3)) (5.7.1)
Requirement already satisfied: bokeh<2.5.0,>=2.4.0 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from panel->panel-chemistry==0.2.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 7)) (2.4.3)
Requirement already satisfied: markdown in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from panel->panel-chemistry==0.2.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 7)) (3.5.2)
Requirement already satisfied: param>=1.12.0 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from panel->panel-chemistry==0.2.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 7)) (1.13.0)
Requirement already satisfied: bleach in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from panel->panel-chemistry==0.2.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 7)) (6.1.0)
Requirement already satisfied: pyct>=0.4.4 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from panel->panel-chemistry==0.2.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 7)) (0.5.0)
Requirement already satisfied: pyviz-comms>=0.7.4 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from panel->panel-chemistry==0.2.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 7)) (3.0.1)
Requirement already satisfied: Jinja2>=2.9 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from bokeh<2.5.0,>=2.4.0->panel->panel-chemistry==0.2.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 7)) (3.1.2)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from bokeh<2.5.0,>=2.4.0->panel->panel-chemistry==0.2.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 7)) (6.0)
Requirement already satisfied: click>=8.0 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from Flask<3.1,>=1.0.4->dash>=2.0.0->molplotly==1.1.7->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 3)) (8.1.7)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from Flask<3.1,>=1.0.4->dash>=2.0.0->molplotly==1.1.7->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 3)) (2.1.2)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets==8.0.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 1)) (0.8.3)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat->molplotly==1.1.7->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 3)) (0.10.6)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat->molplotly==1.1.7->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 3)) (2023.12.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat->molplotly==1.1.7->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 3)) (23.2.0)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat->molplotly==1.1.7->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 3)) (0.33.0)
Requirement already satisfied: entrypoints in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets==8.0.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 1)) (0.4)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from jupyter-core->nbformat->molplotly==1.1.7->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 3)) (4.2.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets==8.0.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 1)) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=6.1.0->ipywidgets==8.0.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 1)) (0.2.13)
Requirement already satisfied: webencodings in /usr/local/envs/ssu-lab-pyqsar3/lib/python3.9/site-packages (from bleach->panel->panel-chemistry==0.2.2->-r /content/pyqsar3/condaenv.vv6z0ghd.requirements.txt (line 7)) (0.5.1)
Building wheels for collected packages: molplotly, pubchempy
  Building wheel for molplotly (setup.py): started
  Building wheel for molplotly (setup.py): finished with status 'done'
  Created wheel for molplotly: filename=molplotly-1.1.7-py3-none-any.whl size=14047 sha256=79f090e9a5c8f1f6f00a4d3564f9321779862a50935e124b3b4410e7dde9e035
  Stored in directory: /root/.cache/pip/wheels/b7/2c/0b/ded174849b6e7f64f135d335ee794527fd31bdf3c15acb16be
  Building wheel for pubchempy (setup.py): started
  Building wheel for pubchempy (setup.py): finished with status 'done'
  Created wheel for pubchempy: filename=PubChemPy-1.0.4-py3-none-any.whl size=13819 sha256=8591f7f529cf77c16639c78804e1ba7b8977e754acdc8dd85a3def274549c4e4
  Stored in directory: /root/.cache/pip/wheels/32/99/db/35883cee90f65dd368ecba4fe42f322792c66dffbb0f6f8100
Successfully built molplotly pubchempy
Installing collected packages: py3dmol, pubchempy, padelpy, dash-table, dash-html-components, dash-core-components, widgetsnbextension, tqdm, tenacity, retrying, oauthlib, numpy, jupyterlab-widgets, ansi2html, scipy, requests-oauthlib, rdkit-pypi, plotly, pandas, contourpy, scikit-learn, matplotlib, dash, panel-chemistry, jupyter-dash, ipywidgets, molplotly
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.66.2
    Uninstalling tqdm-4.66.2:
      Successfully uninstalled tqdm-4.66.2
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.3
    Uninstalling numpy-1.22.3:
      Successfully uninstalled numpy-1.22.3
  Attempting uninstall: scipy
    Found existing installation: scipy 1.8.1
    Uninstalling scipy-1.8.1:
      Successfully uninstalled scipy-1.8.1
  Attempting uninstall: pandas
    Found existing installation: pandas 1.4.2
    Uninstalling pandas-1.4.2:
      Successfully uninstalled pandas-1.4.2
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.2
    Uninstalling scikit-learn-1.0.2:
      Successfully uninstalled scikit-learn-1.0.2
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.5.2
    Uninstalling matplotlib-3.5.2:
      Successfully uninstalled matplotlib-3.5.2
Successfully installed ansi2html-1.9.1 contourpy-1.2.0 dash-2.16.1 dash-core-components-2.0.0 dash-html-components-2.0.0 dash-table-5.0.0 ipywidgets-8.0.2 jupyter-dash-0.4.2 jupyterlab-widgets-3.0.10 matplotlib-3.7.1 molplotly-1.1.7 numpy-1.24.2 oauthlib-3.2.2 padelpy-0.1.13 pandas-1.5.3 panel-chemistry-0.2.2 plotly-5.13.1 pubchempy-1.0.4 py3dmol-2.0.3 rdkit-pypi-2022.9.5 requests-oauthlib-1.3.1 retrying-1.3.4 scikit-learn-1.2.2 scipy-1.10.1 tenacity-8.2.3 tqdm-4.65.0 widgetsnbextension-4.0.10done

**Comment by Ash100** [comment]
More over, I ran individual cells and install pubchempy. Next the import generates an error for panel_chemistry, i repeat the installation and error reaches to,
>ImportError: cannot import name 'HTMLBOX' from 'bokeh.models' (/usr/local/lib/python3.10/dist-packages/bokeh/models/__init__.py)

**Comment by Takshan** [comment]
> More over, I ran individual cells and install pubchempy. Next the import generates an error for panel_chemistry, i repeat the installation and error reaches to,
> 
> > ImportError: cannot import name 'HTMLBOX' from 'bokeh.models' (/usr/local/lib/python3.10/dist-packages/bokeh/models/**init**.py)


Pubchempy and panel_chemistry are both already pinned into the env file, so there is no need to resinstall. However, if you resinstall a newer version, it might cause an issue. Can you retry without reinstalling.

**Comment by Ash100** [comment]
In that case, it generates the error, 
[ModuleNotFoundError: No module named 'pubchempy'].

I have also shared installation log where pubchempy was successfully installed from the list of pinned programs.

**Comment by Takshan** [comment]
> In that case, it generates the error, [ModuleNotFoundError: No module named 'pubchempy'].
> 
> I have also shared installation log where pubchempy was successfully installed from the list of pinned programs.

can you run `which python` to check if it is using the env python.

**Comment by Ash100** [comment]
Sure. let me try `which python`.
Well it prints, '/usr/local/bin/python'. and 'python --version' says, 'Python 3.10.13'

**Comment by Takshan** [comment]
> Sure. let me try `which python`. Well it prints, '/usr/local/bin/python'. and 'python --version' says, 'Python 3.10.13'

You are not using the correct env. please refer to [conda documentation](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment) for setting env.
